<?php
/* Copyright (C) 2016 Stephan Kreutzer
 *
 * This file is part of refugee-it.de.
 *
 * refugee-it.de is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License version 3 or any later version,
 * as published by the Free Software Foundation.
 *
 * refugee-it.de is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License 3 for more details.
 *
 * You should have received a copy of the GNU Affero General Public License 3
 * along with refugee-it.de. If not, see <http://www.gnu.org/licenses/>.
 */



define("LANG_PAGETITLE", "Bietigheim-Bissingen");
define("LANG_HEADER", "74321 Bietigheim-Bissingen");
define("LANG_HEADER_COMPUTER", "Computer");
define("LANG_SECTION_NOTEBOOKS", "Notebooks");
define("LANG_SECTION_PCS", "PCs");
define("LANG_SECTION_PERIPHERALS", "Peripherie");
define("LANG_EXPLANATION_DEPOSIT", "„Pfand“ bedeutet: Sie können den Computer 1-3 Wochen testen, dann das Pfand abgeben, entweder total oder einen Teil per Monat, und wenn Sie den Computer größtenteils intakt zurückgeben, bekommen Sie das Pfand zurück.");
define("LANG_KEYBOARD_GERMANARABIC", "Tastatur Deutsch/Arabisch");
define("LANG_KEYBOARD_STICKER_ARABIC", "Tastaturaufkleber Arabisch");
define("LANG_STATUS_AVAILABLE", "Erhältlich: ");
define("LANG_STATUS_NOT_AVAILABLE", "Nicht erhältlich. ");
define("LANG_DESCRIPTION_NOTEBOOK_16", "Lenovo ThinkPad R60e mit Intel-Celeron-M-Prozessor „410“ (32-Bit-Architektur). Der Prozessor wird mit einer Taktrate von 1460 Megahertz betrieben. 1024 Megabyte Arbeitsspeicher, Festplatte hat 37 Gigabyte. CD/DVD-Laufwerk, 3 USB-Anschlüsse, VGA-Anschluss, Mikrofon-/Tonausgang-Anschlüsse. WLAN, Netzwerkanschluss (RJ45), Modemanschluss (RJ11). PCMCIA-Erweiterungsschacht, ExpressCard-Erweiterungsschacht scheint blockiert. Deutsches Tastaturlayout, TrackPoint. Akku-Kapazität reicht mindestens 20 Minuten, Ladekabel inklusive. Es scheint keine größere Auflösung als 1024x768 Pixel unterstützt zu werden. GNU/Linux Trisquel 7.0 „Belenos“ (mit Langzeitunterstützung) als Betriebssystem vorinstalliert (Live-DVD enthalten). 20,00 Euro Pfand.");
define("LANG_DESCRIPTION_NOTEBOOK_15", "Lenovo ThinkPad T61 mit Intel-Core-2-Duo-Prozessor „T8300“ (64-Bit-Architektur). Die zwei Prozessorkerne werden mit einer Taktrate von 2400 Megahertz betrieben. 2048 Megabyte Arbeitsspeicher, Festplatte hat 100 Gigabyte. CD/DVD-Laufwerk, DVD-Brenner, 3 USB-Anschlüsse, VGA-Anschluss, SDHC-Kartenleser, Mikrofon-/Tonausgang-Anschlüsse. WLAN sowohl intern ohne Treiberunterstützung als auch extern mithilfe eines Edimax IEEE802.11b/g/n-Nano-USB-Adapters „EW-7811UN“ für 150 Mbit pro Sekunde, Netzwerkanschluss (RJ45), Modemanschluss (RJ11), Bluetooth. PCMCIA-Erweiterungsschacht, ExpressCard-Erweiterungsschacht. Deutsches Tastaturlayout, Touchpad und TrackPoint. Akku-Kapazität reicht mindestens 20 Minuten, Ladekabel inklusive. Display-Scharniere etwas wackelig. GNU/Linux Trisquel 7.0 „Belenos“ (mit Langzeitunterstützung) als Betriebssystem vorinstalliert (Live-DVD enthalten). 40,00 Euro Pfand.");
define("LANG_DESCRIPTION_NOTEBOOK_14", "Lenovo ThinkPad R60 mit Intel-Core-2-Duo-Prozessor „T5600“ (64-Bit-Architektur). Die zwei Prozessorkerne werden mit einer Taktrate von 1830 Megahertz betrieben. 2048 Megabyte Arbeitsspeicher, Festplatte hat 640 Gigabyte. CD/DVD-Laufwerk/Brenner, 3 USB-Anschlüsse, VGA-Anschluss, S-Video-Anschluss, 4-Pin-Firewire-Anschluss, Mikrofon-/Tonausgang-Anschlüsse. WLAN intern ohne Treiberunterstützung und defekt, ohne Deaktivierung führt die Komponente zu 100% Prozessorauslastung. WLAN extern mithilfe eines Edimax IEEE802.11b/g/n-Nano-USB-Adapters „EW-7811UN“ für 150 Mbit pro Sekunde, Netzwerkanschluss (RJ45), Modemanschluss (RJ11), Bluetooth. PCMCIA-Erweiterungsschacht, ExpressCard-Erweiterungsschacht. Deutsches Tastaturlayout, Touchpad und TrackPoint. Akku-Kapazität reicht mindestens 20 Minuten, Ladekabel inklusive. Display-Scharniere etwas wackelig. GNU/Linux Trisquel 7.0 „Belenos“ (mit Langzeitunterstützung) als Betriebssystem vorinstalliert (Live-DVD enthalten). 30,00 Euro Pfand.");
define("LANG_DESCRIPTION_NOTEBOOK_13", "Dell Latitude D620 mit Intel-Core-2-Duo-Prozessor „T2400“ (32-Bit-Architektur). Die zwei Prozessorkerne werden mit einer Taktrate von 1830 Megahertz betrieben. 1024 Megabyte So-Dimm DDR2 Arbeitsspeicher, SATA-Festplatte hat 80 Gigabyte, Displaydiagonale ist 14,1 Zoll für WXGA (1280x800 Pixel, Verhältnis 16:10). CD/DVD-Laufwerk, 4 USB-Anschlüsse, VGA-Anschluss, serieller Anschluss, Mikrofon-/Tonausgang-Anschlüsse. WLAN, 10/100/1000-Megabit-pro-Sekunde-Netzwerkanschluss (RJ45), Modemanschluss (RJ11), Infrarot womöglich ohne Treiberunterstützung. PCMCIA-Erweiterungsschacht. Tastatur hat United-Kingdom-Layout, Touchpad und TrackPoint. Akku-Kapazität reicht mindestens 20 Minuten, Ladekabel inklusive. GNU/Linux Trisquel 7.0 „Belenos“ (mit Langzeitunterstützung) als Betriebssystem vorinstalliert (Live-DVD enthalten). 30,00 Euro Pfand.");
define("LANG_DESCRIPTION_NOTEBOOK_12", "Lenovo 3000 N200 mit Intel-Celeron-Prozessor „530“ (64-Bit-Architektur). Der Prozessor wird mit einer Taktrate von 1730 Megahertz betrieben. 2456 Megabyte Arbeitsspeicher, Festplatte hat 120 Gigabyte. CD/DVD-Laufwerk/Brenner, 4 USB-Anschlüsse, 4-Pin-Firewire-Anschluss, VGA-Anschluss, 7-Pin-Mini-DIN-S-Video-Anschluss, SDHC-Kartenleser, Mikrofon-/Tonausgang-Anschlüsse. WLAN sowohl intern ohne Treiberunterstützung als auch extern mithilfe eines Edimax IEEE802.11b/g/n-Nano-USB-Adapters „EW-7811UN“ für 150 Mbit pro Sekunde, Netzwerkanschluss (RJ4), Modemanschluss (RJ11), Bluetooth. ExpressCard-Erweiterungsschacht. Deutsches Tastaturlayout, Touchpad. Akku-Kapazität reicht mindestens 20 Minuten, Ladekabel inklusive. Die Gehäuseecke links unten bei aufgeklapptem Notebook ist gebrochen, wurde aber geklebt. GNU/Linux Trisquel 7.0 „Belenos“ (mit Langzeitunterstützung) als Betriebssystem vorinstalliert (Live-DVD enthalten). 30,00 Euro Pfand.");
define("LANG_DESCRIPTION_NOTEBOOK_11", "Samsung R519 mit Intel-Celeron-Dual-Core-Prozessor „T4200“ (64-Bit-Architektur). Die zwei Prozessorkerne werden mit einer Taktrate von 2200 Megahertz betrieben. 2048 Megabyte So-Dimm DDR2 Arbeitsspeicher, SATA-Festplatte hat 250 Gigabyte. Displaydiagonale ist 15,6 Zoll für WXGA (1366x768 Pixel). CD/DVD-Laufwerk/Brenner, 3 USB-Anschlüsse, VGA-Anschluss, SDHC-Kartenleser, Mikrofon-/Tonausgang-Anschlüsse, Webcam, WLAN, 10/100/1000-Megabit-pro-Sekunde-Netzwerkanschluss (RJ45). Deutsches Tastaturlayout, Touchpad. Akku-Kapazität ist gut, Ladekabel inklusive. Display spiegelt stark und Helligkeit lässt sich nicht einstellen, rechter Lautsprecher defekt. GNU/Linux Trisquel 7.0 „Belenos“ (mit Langzeitunterstützung) als Betriebssystem vorinstalliert (Live-DVD enthalten). 50,00 Euro Pfand.");
define("LANG_DESCRIPTION_NOTEBOOK_7", "Lenovo ThinkPad X200s mit Intel-Centrino-Core-2-Duo-Prozessor „L9300“ (64-Bit-Architektur). Die zwei Prozessorkerne werden mit einer Taktrate von 1600 Megahertz betrieben. 2048 Megabyte So-Dimm DDR3 Arbeitsspeicher, SATA-Festplatte hat 80 Gigabyte, Displaydiagonale ist 12,1 Zoll für WXGA (1280x800 Pixel, Verhältnis 16:10). 3 USB-Anschlüsse, VGA-Anschluss, SDHC-Kartenleser, Mikrofon-/Tonausgang-Anschlüsse. WLAN sowohl intern ohne Treiberunterstützung als auch extern mithilfe eines Edimax IEEE802.11b/g/n-Nano-USB-Adapters „EW-7811UN“ für 150 Mbit pro Sekunde, 10/100/1000-Megabit-pro-Sekunde-Netzwerkanschluss (RJ4), Bluetooth. ExpressCard-Erweiterungsschacht. Deutsches Tastaturlayout und TrackPoint. Akku-Kapazität ist gut, Ladekabel inklusive. Kein Laufwerk für Wechselmedien! GNU/Linux Trisquel 7.0 „Belenos“ (mit Langzeitunterstützung) als Betriebssystem vorinstalliert (Live-DVD enthalten). 40,00 Euro Pfand.");
define("LANG_DESCRIPTION_NOTEBOOK_4", "Lenovo ThinkPad T60 mit Intel-Core-2-Duo-Prozessor „T2400“ (32-Bit-Architektur). Die zwei Prozessorkerne werden mit einer Taktrate von 1830 Megahertz betrieben. 2048 Megabyte So-Dimm DDR2 Arbeitsspeicher, SATA-Festplatte hat 80 Gigabyte. Displaydiagonale ist 14,1 Zoll für XGA (1024x768 Pixel, Verhältnis 04:03). CD/DVD-Laufwerk/Brenner, 3 USB-Anschlüsse, VGA-Anschluss, Mikrofon-/Tonausgang-Anschlüsse. WLAN sowohl intern ohne Treiberunterstützung als auch extern mithilfe eines Edimax IEEE802.11b/g/n-Nano-USB-Adapters „EW-7811UN“ für 150 Mbit pro Sekunde, 10/100/1000-Megabit-pro-Sekunde-Netzwerkanschluss (RJ45), Modemanschluss (RJ11), Bluetooth, Infrarot womöglich ohne Treiberunterstützung. PCMCIA-Erweiterungsschacht, ExpressCard-Erweiterungsschacht. Tastatur hat United-Kingdom-Layout, Touchpad und TrackPoint. Akku-Kapazität reicht mindestens 20 Minuten, Ladekabel inklusive. 1 Pixelfehler. GNU/Linux Trisquel 7.0 „Belenos“ (mit Langzeitunterstützung) als Betriebssystem vorinstalliert (Live-DVD enthalten). 40,00 Euro Pfand.");
define("LANG_DESCRIPTION_NOTEBOOK_3", "Lenovo ThinkPad X200 mit Intel-Core-2-Duo-Prozessor „P8600“ (64-Bit-Architektur). Die zwei Prozessorkerne werden mit einer Taktrate von 2400 Megahertz betrieben. 2048 Megabyte So-Dimm DDR2 Arbeitsspeicher, SATA-Festplatte hat 160 Gigabyte, Displaydiagonale ist 12,1 Zoll für WXGA (1280x800 Pixel, Verhältnis 16:10). 3 USB-Anschlüsse, VGA-Anschluss, SDHC-Kartenleser, Mikrofon-/Tonausgang-Anschlüsse. WLAN sowohl intern ohne Treiberunterstützung als auch extern mithilfe eines Edimax IEEE802.11b/g/n-Nano-USB-Adapters „EW-7811UN“ für 150 Mbit pro Sekunde, 10/100/1000-Megabit-pro-Sekunde-Netzwerkanschluss (RJ45), Modemanschluss (RJ11), Bluetooth. ExpressCard-Erweiterungsschacht. Tastatur hat United-Kingdom-Layout und TrackPoint. Akku-Kapazität reicht mindestens 20 Minuten, Ladekabel inklusive. Gehäuse leicht verschmutzt. Kein Laufwerk für Wechselmedien! GNU/Linux Trisquel 7.0 „Belenos“ (mit Langzeitunterstützung) als Betriebssystem vorinstalliert (Live-DVD enthalten). 40,00 Euro Pfand.");
define("LANG_DESCRIPTION_NOTEBOOK_2", "Dell Latitude D430 mit Intel-Core-2-Duo-Prozessor „U7600“ (64-Bit-Architektur). Die zwei Prozessorkerne werden mit einer Taktrate von 1200 Megahertz betrieben. 2048 Megabyte So-Dimm DDR2 Arbeitsspeicher, ZIF-Festplatte hat 80 Gigabyte, Displaydiagonale ist 12,1 Zoll für WXGA (1280x800 Pixel, Verhältnis 16:10). 3 USB-Anschlüsse, 4-Pin-Firewire-Anschluss, VGA-Anschluss, SDHC-Kartenleser, Mikrofon-/Tonausgang-Anschlüsse. WLAN sowohl intern ohne Treiberunterstützung als auch extern mithilfe einer PCMCIA-IEEE-802.11b-Erweiterungskarte von Gericom, Netzwerkanschluss (RJ45), Modemanschluss (RJ11). Tastatur hat United-Kingdom-Layout, Touchpad und TrackPoint. Akku-Kapazität reicht mindestens 20 Minuten, Ladekabel inklusive. Kein Laufwerk für Wechselmedien! GNU/Linux Trisquel 7.0 „Belenos“ (mit Langzeitunterstützung) als Betriebssystem vorinstalliert (Live-DVD enthalten). 40,00 Euro Pfand.");
define("LANG_DESCRIPTION_NOTEBOOK_1", "IBM ThinkPad R51 mit Intel-Pentium-M-Prozessor (32-Bit-Architektur). Der Prozessorkern wird mit einer Taktrate von 1700 Megahertz betrieben. 512 Megabyte DDR-Arbeitsspeicher, ATA-Festplatte hat 40 Gigabyte, DVD-Laufwerk mit CD-RW-Brennfunktion. Displaydiagonale ist 14 Zoll für XGA (1024x768 Pixel, Verhältnis 04:03). 2 USB-Anschlüsse, VGA-Anschluss, Mikrofon-/Tonausgang-Anschlüsse, paralleler Anschluss, Apple-Desktop-Bus-Anschluss. WLAN, 10/100-Megabit-pro-Sekunde-Netzwerkanschluss (RJ45), Modemanschluss (RJ11). PCMCIA-Erweiterungsschacht, ExpressCard-Erweiterungsschacht. Tastatur hat United-Kingdom-Layout, Touchpad und Trackpoint. Akku-Kapazität reicht mindestens 20 Minuten, Ladekabel inklusive. GNU/Linux gNewSense 3.1 „Parkes“ als Betriebssystem vorinstalliert (Live-DVD enthalten). 20,00 Euro Pfand.");
define("LANG_DESCRIPTION_PC_1", "Hewlett-Packard dc7700 Convertible Minitower mit Intel-Pentium-4-Prozessor „HT“ (64-Bit-Architektur). Der Prozessorkern wird mit einer Taktrate von 3200 Megahertz betrieben. 2048 Megabyte DDR2 Arbeitsspeicher für bis zu Front-Side-Bus PC667 (667 Megahertz), SATA-Festplatte hat 80 Gigabyte. 2 USB-Anschlüsse vorne, Mikrofon-/Tonausgang-Anschlüsse vorne, 3,5-Zoll-Diskettenlaufwerk, CD/DVD-Laufwerk/Brenner, 6 USB-Anschlüsse hinten, PS/2-Maus- und Tastaturanschluss hinten, VGA-Anschluss hinten, serieller Anschluss hinten, paralleler Anschluss hinten, Mikrofon-/Tonausgang-/Toneingang-Anschlüsse hinten, 10/100/1000-Megabit-pro-Sekunde-Netzwerkanschluss (RJ45) hinten. Grafikkarte auf dem Motherboard. Mit Netzkabel, Netzteil 350 Watt. In Midi-Tower-Gehäuse. Kein WLAN, keine Peripheriegeräte! GNU/Linux Trisquel 7.0 „Belenos“ (mit Langzeitunterstützung) als Betriebssystem vorinstalliert (Live-DVD enthalten). 20,00 Euro Pfand.");
define("LANG_CDDVD_READERWRITER_EXTERNAL", "CD/DVD-Laufwerk/Brenner extern");
define("LANG_DESCRIPTION_CDDVD_READERWRITER_EXTERNAL", "20,00 Euro Pfand.");
define("LANG_DESCRIPTION_KEYBOARD_GERMANARABIC", "Tastatur Deutsch/Arabisch von Fujitsu Siemens, USB-Anschluss. 15,00 Euro Pfand.");
define("LANG_DESCRIPTION_KEYBOARD_STICKER_ARABIC", "Tastatursticker Arabisch in rot. 0,00 Euro Pfand.");
define("LANG_PRETEXT", "Bitte%20Kontaktinformationen%20und%20diese%20ID%20senden%3A%20");
define("LANG_REQUEST_NOW", "Jetzt anfragen");
define("LANG_REQUEST_SIMILAR", "Jetzt nach ähnlichem Angebot fragen");



?>
